In [1]:
import urllib.request as ur
import re
import pandas as pd
from pandas import ExcelWriter
from pandas import ExcelFile

request = ur.Request("http://www.bolsamadrid.es/esp/aspx/Mercados/Precios.aspx?indice=ESI100000000")
result = ur.urlopen(request)
content = result.read().decode()



exp_tabla = '.*?<table.*?id="ctl00_Contenido_tblAcciones".*?".*?>(.*?)</table>.*?'
tabla = re.findall(exp_tabla,content,re.DOTALL)
#Hecho
exp_compañias ='.*?<td.*?align="left">.*?<a.*?>(.*?)</a>*?'
#Hecho
exp_ultimos ='.*?<td class="DifFl.*?" align="left">.*?<td>(.*?)</td>.*?'
#Hecho
exp_diferencias = '.*?<td>.*?</td>.*?<td class="DifCl.*?">(.*?)</td>.*?<td>.*?</td>.*?'
#Hecho
exp_minimos = '.*?<td>([0-9]+,[0-9]+)</td><td>[0-9]+\.[0-9]+.*?</td>.*?'
#Hecho
exp_maximos = '.*?<td class="DifCl.*?">.*?<td>(.*?)</td>.*?'
#Hecho
exp_efectivos = '<td>[0-9]+\..*?[0-9]+.>*?</td>.*?<td>([0-9]+\.[0-9]+,[0-9]+)</td>.*?'
#Hecho
exp_volumen = '<td>([0-9]+?\.?[0-9]+\.[0-9]+)</td>.*?<td>[0-9]+\.[0-9]+,[0-9]+</td>.*?'
#Hecho
exp_fechas = '.*?<td>[0-9]+\.[0-9]+,[0-9]+</td>.*?<td.*?>(.*?)</td>.*?'
#Hecho
exp_horas = '.*?<td class="Ult" align="center">(.*?)</td>.*?</tr>'

#Listas
compañias = []
ultimos = []
diferencias = []
maximos = []
minimos = []
efectivos = []
volumenes = []
fechas = []
horas = []

#Funciones
def getCompañias(compañias):
    compañias.append(re.findall(exp_compañias,content,re.DOTALL))
    compañias[0].pop(0)
    
def getUltimos(ultimos):
    ultimos.append(re.findall(exp_ultimos,''.join(tabla),re.DOTALL))    
    
def getDiferencias(diferencias):
    diferencias.append(re.findall(exp_diferencias,''.join(tabla),re.DOTALL))

def getMaximos(maximos):
    maximos.append(re.findall(exp_maximos,''.join(tabla),re.DOTALL))

def getMinimos(minimos):
    minimos.append(re.findall(exp_minimos,''.join(tabla),re.DOTALL))
    
def getEfectivo(efectivos):
    efectivos.append(re.findall(exp_efectivos,''.join(tabla),re.DOTALL))

def getVolumen(volumenes):
    volumenes.append(re.findall(exp_volumen,''.join(tabla),re.DOTALL))
    
def getFecha(fechas):
    fechas.append(re.findall(exp_fechas,''.join(tabla),re.DOTALL))
    
def getHoras(horas):
    horas.append(re.findall(exp_horas,''.join(tabla),re.DOTALL))

    #Obtención de los datos de la tabla de acciones de la Bolsa de Madrid
#def obtenerDatosAcciones():
getCompañias(compañias)
getUltimos(ultimos)
getDiferencias(diferencias)
getMaximos(maximos)
getMinimos(minimos)
getEfectivo(efectivos)
getVolumen(volumenes)
getFecha(fechas)
getHoras(horas)

#def ListadeListatoLista():
compañia = compañias.pop(0)
ultimo = ultimos.pop(0)
diferencia = diferencias.pop(0)
maximo = maximos.pop(0)
minimo = minimos.pop(0)
efectivo = efectivos.pop(0)
volumen = volumenes.pop(0)
fecha = fechas.pop(0)
hora = horas.pop(0)

#def pandaToExcel():
 #Creamos los pandas para visualizar los datos
acciones = {'Compañía' : compañia ,'Último' : ultimo ,'Diferencia': diferencia ,'Máximo':maximo ,'Mínimo':minimo,'Efectivo' : efectivo,'Volumen':volumen,'Fecha': fecha,'Hora':hora} 
df = pd.DataFrame.from_dict(acciones)
writer = ExcelWriter('Acciones1.xlsx')
df.to_excel(writer,'Sheet1',index=False)
writer.save() 
df

,Compañía,Diferencia,Efectivo,Fecha,Hora,Máximo,Mínimo,Volumen,Último
0,ACCIONA,"0,78","8.600,86",05/03/2019,Cierre,"89,9000","88,0200",96.238,"89,9000"
1,ACERINOX,"-0,48","7.451,83",05/03/2019,Cierre,"9,6360","9,4120",784.676,"9,4560"
2,ACS,"-1,13","36.434,03",05/03/2019,Cierre,"39,9800","39,3400",920.429,"39,5500"
3,AENA,"1,24","32.246,07",05/03/2019,Cierre,"159,3000","156,9000",203.022,"159,3000"
4,AMADEUS,"-0,64","59.744,62",05/03/2019,Cierre,"66,2400","65,2600",912.085,"65,4400"
5,ARCELORMIT.,"-1,62","8.373,44",05/03/2019,Cierre,"20,3000","19,9200",417.387,"20,0350"
6,BA.SABADELL,"-0,09","22.161,45",05/03/2019,Cierre,"1,0240","0,9878",22.147.387,"0,9996"
7,BA.SANTANDER,"0,06","118.857,82",05/03/2019,Cierre,"4,2750","4,2115",28.028.146,"4,2440"
8,BANKIA,"-0,15","14.372,08",05/03/2019,Cierre,"2,7040","2,6640",5.354.289,"2,6830"
9,BANKINTER,"0,78","15.261,34",05/03/2019,Cierre,"7,2480","7,1300",2.120.075,"7,2000"
10,BBVA,"-0,54","119.905,46",05/03/2019,Cierre,"5,3900","5,2450",22.563.005,"5,3070"
11,CAIXABANK,"-0,03","33.557,92",05/03/2019,Cierre,"3,1240","3,0740",10.819.678,"3,1060"
12,CELLNEX,"2,03","25.013,69",05/03/2019,Cierre,"24,6100","23,7000",1.032.593,"24,1800"
13,CIE AUTOMOT.,"0,64","4.725,69",05/03/2019,Cierre,"25,2800","24,7000",188.387,"25,2800"
14,ENAGAS,"-1,00","22.424,05",05/03/2019,Cierre,"24,9200","24,6100",908.455,"24,6400"
15,ENCE,"-2,99","12.235,88",05/03/2019,Cierre,"6,5200","6,2050",1.936.793,"6,3250"
16,ENDESA,"-0,37","26.540,62",05/03/2019,Cierre,"21,9200","21,6600",1.216.941,"21,8100"
17,FERROVIAL,"-0,05","28.284,26",05/03/2019,Cierre,"20,9100","20,5800",1.359.642,"20,8600"
18,GRIFOLS CL.A,"0,12","12.107,15",05/03/2019,Cierre,"24,2800","23,9500",500.907,"24,2200"
19,IAG,"0,30","23.384,75",05/03/2019,Cierre,"6,7280","6,6340",3.502.216,"6,6900"
20,IBERDROLA,"0,52","75.561,20",05/03/2019,Cierre,"7,3720","7,2900",10.288.939,"7,3500"
21,INDITEX,"-0,26","90.496,63",05/03/2019,Cierre,"26,9300","26,4600",3.382.444,"26,7900"
22,INDRA A,"-1,94","5.888,92",05/03/2019,Cierre,"10,0400","9,8400",595.537,"9,8450"
23,INM.COLONIAL,"0,11","5.633,32",05/03/2019,Cierre,"9,1200","8,9950",621.305,"9,0700"
24,MAPFRE,"-0,64","7.034,23",05/03/2019,Cierre,"2,5010","2,4710",2.833.414,"2,4800"
25,MEDIASET,"-0,68","13.049,40",05/03/2019,Cierre,"7,1480","6,9160",1.861.915,"6,9760"
26,MELIA HOTELS,"-1,25","4.189,18",05/03/2019,Cierre,"8,8000","8,6400",482.344,"8,6700"
27,MERLIN,"1,48","9.019,43",05/03/2019,Cierre,"11,3400","11,1600",798.935,"11,3400"
28,NATURGY,"0,21","47.502,23",05/03/2019,Cierre,"23,8900","23,6000",1.999.848,"23,7700"
29,R.E.C.,"-1,86","50.039,25",05/03/2019,Cierre,"18,5400","18,3300",2.711.560,"18,4650"
30,REPSOL,"-0,10","63.919,97",05/03/2019,Cierre,"15,1150","15,0100",4.242.114,"15,0850"
31,SIEMENS GAME,"-1,60","18.653,51",05/03/2019,Cierre,"13,4150","13,1300",1.408.833,"13,2200"
32,TEC.REUNIDAS,"0,53","3.883,84",05/03/2019,Cierre,"24,9800","24,5500",156.710,"24,8300"
33,TELEFONICA,"0,89","90.487,43",05/03/2019,Cierre,"7,5560","7,4280",12.073.210,"7,4900"
34,VISCOFAN,"-0,36","4.294,66",05/03/2019,Cierre,"55,8500","55,2500",77.475,"55,4000"